config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show] # route only for index and show

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolis, except: [:show] do
    put :sort, on: :collection
  end
  
  # get 'portfolio', to: 'portfolis#index'
  get 'portfolis/:id', to: 'portfolis#show', as: 'portfoli_show'
  get 'anuglar-items', to: 'portfolis#angular'

  get 'about-me', to: 'pages#about'	# get 'pages/about'
  get 'contact', to: 'pages#contact'	# get 'pages/contact'
  get 'tech-news', to: 'pages#tech_news' # twitter API

  resources :blogs do
  	member do
  		get :toggle_status   # toggle_status_blog_path(blog)
  	end												#                       id
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'  # can call anything , # get 'pages/home'
end

app/models/portfoli.rb
class Portfoli < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.anuglar
    where(subtitle: "Angular")
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

end

app/controllers/portfolis_controller.rb
class PortfolisController < ApplicationController
	before_action :set_portfolio_item, only: [:edit, :update , :show, :destroy]
	layout 'portfolio' # use portfolio layout
	access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

	def index
		# @portfolio_items = Portfoli.all
		@portfolio_items = Portfoli.by_position
	end

	def angular
		@angular_portfolio_items = Portfoli.anuglar
	end

	def sort
		params[:order].each do |key, value|
			Portfoli.find(value[:id]).update(position: value[:position])
		end

		render nothing: true
	end

	def new
		@portfolio_item = Portfoli.new
	end

	def create
		@portfolio_item = Portfoli.new(portfolio_params)

		respond_to do |format|
			if @portfolio_item.save
				format.html {redirect_to portfolis_path, notice: 'Your portfolio is now live.' }
			else
				format.html {render :new}
			end
		end
	end

	def edit
	end

	def update

		respond_to do |format|
			if @portfolio_item.update(portfolio_params)
				format.html { redirect_to portfolis_path, notice: "Your portfolio is successfully updated."}
			else												# /portfolis
				format.html {render :edit}
			end
		end
	end

	def show
	end

	def destroy
		# Destroy/delete the record
		@portfolio_item.destroy

		# Redirect
		respond_to do |format|
			format.html { redirect_to portfolis_url, notice: 'The portfolio was removed.'}
		end
	end

	
	private

	def portfolio_params
		params.require(:portfoli).permit(:title, 
																		 :subtitle, 
																		 :body,
																		 :main_image,
																		 :thumb_image, 
																		 technologies_attributes: [:id, :name, :_destroy]
																		)
	end

	def set_portfolio_item # Peform the lookup
		@portfolio_item = Portfoli.find(params[:id])
	end
end

app/helpers/portfolis_helper.rb
module PortfolisHelper
  def image_generator(height:, width: )
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.thumb_image? || img.model.main_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200') # thumb_image
    elsif type == 'main'
      image_generator(height: '600', width: '400') # main_image
    end
  end
end

app/views/portfolis/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: "form-control" %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file<%= f.file_field :main_image, style: 'display:none' %>
        </label>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file<%= f.file_field :thumb_image, style: 'display:none' %>
        </label>
      </div>

    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control", rows: 15 %>
      </div>
    </div>
  </div>  

  <hr>

  <div class="col-md-12">
    <h2>Technologies Used:</h2>
    <%= f.fields_for :technologies do |technology_form| %>
      <%= render 'technology_fields', f: technology_form %>
    <% end %>

    <div> <!-- Bring me the technologies variables right above, f here is different than above f -->
      <%= link_to_add_association 'Add Technology', f, :technologies %>
    </div>


    <div class="form-group">
      <%= f.submit 'Save Protfolio Item', class: 'btn btn-primary btn-block' %>
    </div>

  </div>
<% end %>

app/views/portfolis/_portfolio_item.html.erb
<div class="col-md-4">
	<div class="card" data-id="<%= portfolio_item.id %>">
		<%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'), width: '100%' %> <!-- helper from portfolis_helper.rb -->
		<p class="card-text">
			<span><%= link_to portfolio_item.title, portfoli_show_path(portfolio_item) %></span><%= portfolio_item.subtitle %>
		</p>
	</div>
</div>

app/views/portfolis/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association 'remove Technology', f %>
</div>

app/views/portfolis/angular.html.erb
<h1>Portfolio Angular Items</h1>

<%= link_to "Create New Item", new_portfoli_path if logged_in?(:site_admin) %>
							<!-- /portfolis/new -->


<% @angular_portfolio_items.each do |portfolio_item| %>
	<p><%= link_to portfolio_item.title, portfoli_show_path(portfolio_item) %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
	<%= link_to "Edit", edit_portfoli_path(portfolio_item) %>
	<%= link_to 'Delete Portfolio Item', portfoli_show_path(portfolio_item), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/portfolis/edit.html.erb
<div class="container portfolio-container">
	<h1>Edit a portfolio Item</h1>
	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolis/index.html.erb
<div class="album text-muted">
  <div class="container">
  	<%= source_helper("alert alert-warning") %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>" >

			<!-- < % @portfolio_items.each do |portfolio_item| %> -->
			<%= render partial: 'portfolio_item' , collection: @portfolio_items %>

		</div>
  </div>
</div>

app/views/portfolis/new.html.erb
<div class="container portfolio-container">
	<h1>Create a new portfolio Item</h1>
	<%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolis/show.html.erb
<div class="container portfolio-container">
	<div class="row">

		<div class="col-md-7">
			<%=image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
		</div>

		<div class="col-md-5">
				<h1><%= @portfolio_item.title %></h1>

				<hr>

				<em><%= @portfolio_item.subtitle %></em>
				<p><%= @portfolio_item.body %></p>

				<hr>

				<h3>Technologies Used:</h3>
				<% @portfolio_item.technologies.each do |t| %>
					<p><%= t.name %></p>
				<% end %>

				<% if logged_in?(:site_admin) %>
					<div class="col-md-12">
						<%= link_to "Edit", edit_portfoli_path(@portfolio_item), class: 'btn btn-warning' %>
					</div>
				<% end %>

		</div>
	</div>
</div>