config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show] # route only for index and show

  resources :comments
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolis, except: [:show] do
    put :sort, on: :collection
  end
  
  # get 'portfolio', to: 'portfolis#index'
  get 'portfolis/:id', to: 'portfolis#show', as: 'portfoli_show'
  get 'anuglar-items', to: 'portfolis#angular'

  get 'about-me', to: 'pages#about'	# get 'pages/about'
  get 'contact', to: 'pages#contact'	# get 'pages/contact'
  get 'tech-news', to: 'pages#tech_news' # twitter API

  resources :blogs do
  	member do
  		get :toggle_status   # toggle_status_blog_path(blog)
  	end												#                       id
  end

  mount ActionCable.server => '/cable'

  root to: 'pages#home'  # can call anything , # get 'pages/home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner app-footer">
    <!-- <p>Cover template for <a href="https://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p> -->
    <%= copyright_helper %>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
	<div class="inner">
	  <h3 class="masthead-brand">Thai Nguyen</h3>
	  <nav class="nav nav-masthead app-nav">
	    <%= nav_helper 'nav-link', 'span' %>
		  <%= login_helper 'nav-link' %>
	  </nav>
	</div>
</div>

app/views/shared/_blog_footer.html.erb
<!-- Start of footer -->
<footer class="blog-footer">
  <p>
  	<%= copyright_helper %>
  </p>
  
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>
<!-- End of footer -->

app/views/shared/_blog_masthead.html.erb
<!-- Start of blog header -->
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    <span>
    	<%= link_to 'Create a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    
    <span>
    	<%= link_to "Topic", topics_path %> <!-- to the topic index -->
    </span>

  </div>
</div>
<!-- End of blog header

app/views/shared/_blog_nav.html.erb
<!-- Start of Nav -->
<nav class="navbar navbar-toggleable-md navbar-light bg-faded blog-nav">
  <button class="navbar-toggler navbar-toggler-right" 
	  type="button" data-toggle="collapse" 
	  data-target="#navbarSupportedContent" 
	  aria-controls="navbarSupportedContent" 
	  aria-expanded="false" 
	  aria-label="Toggle navigation">

   <span class="navbar-toggler-icon"></span>
	</button>

  <div class="container">
    <%= link_to "Thai Nguyen", root_path, class: 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <%= nav_helper 'nav-link', 'li' %>  
        <%= login_helper 'nav-link' %>  
      </ul>
    </div>
  </div>
</nav>
<!-- End of Nav -->

app/views/shared/_blog_sidebar.html.erb
<!-- Start of sidebar -->
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>Hello, my name is Thai Nguyen</p>
  </div>

  <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div> 

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon "github-square" %></a></li>
      <li><a href="#"><%= fa_icon "facebook-square" %></a></li>
      <li><a href="#"><%= fa_icon "github-square" %></a></li>
    </ol>
  </div>
</div>
<!-- End of sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolis_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<!-- Start of Footer -->
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolis_path %> /
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_helper %></p>
  </div>
</footer>
<!-- End of Footer -->

app/views/shared/_portfolio_masthead.html.erb
<!-- Start of Masthead -->
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">This is my Projects</p>
    <p>
      <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
    </p>
  </div>
</section>
<!-- End of Masthead -->

app/views/shared/_portfolio_nav.html.erb
<!-- Start of Navigation -->
<div class="collapse bg-inverse" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper "text-white" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="navbar navbar-inverse bg-inverse">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Thai Nguyen</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>
<!-- End of Navigation -->